### ISSUE TITLE
Incorrect window title

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/io.github.ec_.Quake3e.OpenArena#115]
It looks like that the window title is always set to "Quake 3: Arena" instead of "OpenArena":

![openarena_title](https://github.com/flathub/io.github.ec_.Quake3e.OpenArena/assets/2339930/e8aade11-b935-44ad-b273-e8b5f31b9eb8)

We should probably fix that if possible.

**Comment by xplshn** [comment]
Is there a CVAR that can be set that you know of?

**Comment by xplshn** [comment]
I couldn't find any here: https://github.com/ec-/Quake3e/issues/188

**Comment by AsciiWolf** [comment]
> Is there a CVAR that can be set that you know of?

I don't think so. It most likely is hardcoded in the engine source code.

**Comment by xplshn** [comment]
> > Is there a CVAR that can be set that you know of?
> 
> I don't think so. It most likely is hardcoded in the engine source code.

Are you able to write a patch for it? I am currently busy with school, I've already opened an Issue about this, I am sure no one would mind adding a CVAR to change the Window's title so, if Ec doesn't say anything about it in a week or so I will look into making the patch myself.

**Comment by xplshn** [comment]
Could you check this out? I don't use a DE, I don't have titlebars and my WM doesn't have a way to enable them. https://github.com/flathub/io.github.ec_.Quake3e.OpenArena/pull/117

**Comment by AsciiWolf** [comment]
Sadly, it did not help. Still "Quake 3: Arena" in the window title.

I am too busy with work and other things at the moment so I am sadly not able to take a look at writing the patch myself.

**Comment by xplshn** [comment]
Fixed long time ago, forgot to close the issue.
