### ISSUE TITLE
Difference between this repository and ws.openarena.OpenArena

### ISSUE THREAD

**Issue by 1bcb** [flathub/io.github.ec_.Quake3e.OpenArena#13]
This repository and [this one](https://github.com/flathub/ws.openarena.OpenArena) point to different apps on Flathub.  Both Flathub store pages link to the same upstream website.  This repository seems to be maintained, while the other one isn't.  

1)What is the difference between this manifest and the other one?
2)If this manifest is the replacement for the other one, why are both still on Flathub?

**Comment by xplshn** [comment]
The ws.openarena package was abandoned by the official team. The official website no longer updates its blog, and the official Flatpak has a flawed renderer, you can't change the resolution on the game, if you do you will crash the game, or have it change your xrandr settings, then crash the game, leaving you an unusable 600x600 or 800x600.
Also, this Flatpak uses the Quake3e engine, which has bug fixes, Vulkan support, and better performance.

**Comment by xplshn** [comment]
If you have further questions I'll answer thoroughly. Also check EC's Quake3e's repo.  https://github.com/ec-/Quake3e

Also an intersting Quake site is: https://quakeengines.github.io/
