### ISSUE TITLE
Missing weapon textures since updating to 23.08 runtime

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/io.github.ec_.Quake3e.OpenArena#56]
Parts of the chaingun and chainsaw weapons are missing after the Flatpak got updated to runtime version 23.08.

This is the same issue that I had with my update of the original OpenArena version. See this link for more information: https://github.com/flathub/ws.openarena.OpenArena/pull/14#issuecomment-1708284895

**Comment by slashdevslashurandom** [comment]
If I had to guess why these specific parts of weapons are missing, it might be because these rotate when the weapon is in use. Perhaps the code that handles that rotation doesn't work correctly right now?

**Comment by xplshn** [comment]
Maybe an update in some library used by both game engines? I'm gonna see if updating the engine fixes it.

**Comment by AsciiWolf** [comment]
I have reverted the fd.o runtime to 22.08. I will however keep this ticket open since this is a problem that needs to be addressed.

**Comment by AsciiWolf** [comment]
The next freedesktop-sdk release will contain mesa 23.3.0. We should probably retest this issue after the update.

**Comment by AsciiWolf** [comment]
The 22.08 runtime got updated to mesa 23.3 and there is still no problem with missing weapon parts in OpenArena. So, this issue seems **unrelated to mesa**.

**Comment by xplshn** [comment]
@AsciiWolf I do not much about debugging, but we could make a debug branch and compile with -g, running from the terminal is another great way to log the engine.

**Comment by AsciiWolf** [comment]
That sounds like a good idea.
