### ISSUE TITLE
~/.q3a is used instead of ~/.openarena

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/io.github.ec_.Quake3e.OpenArena#65]
The config directory for io.github.ec_.Quake3e.OpenArena seems to be `~/.q3a` instead of a correct `~/.openarena` one. This should ideally be patched.

**Comment by AsciiWolf** [comment]
Fixed.

**Comment by xplshn** [comment]
Is there any difference? I wanted it to be compatible with Quake3. In the wrapper script, you can see that its possible to start the engine and point it to whatever basegame you want to use. Should I add two dirs? .q3a and .openarena in order for it to be possible to play Quake as well?

**Comment by AsciiWolf** [comment]
`.openarena` is a standard directory used by OpenArena. `.q3a` on the other hand is Quake 3 specific. Compatibility with Quake 3 is kind of out-of-scope of this Flatpak, to be honest. It can be there, but definitely should not be preferred over the OpenArena support that this Flatpak primarily provides. Ideally, if we want Quake 3 support, we can make another Flatpak called `io.github.ec_.Quake3e.Quake3` or similar that does not contain any OpenArena specific patches and focused on Quake 3 support (just like the [ioquake3 Flatpak](https://github.com/flathub/org.ioquake3.ioquake3) does).
