### ISSUE TITLE
qkey does not seem to work

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/io.github.ec_.Quake3e.OpenArena#70]
The qkey creation logic seems to be broken for some reason as pointed out in [this comment](https://github.com/flathub/io.github.ec_.Quake3e.OpenArena/issues/53#issuecomment-1778692941). Because of this, connection to many online servers hangs on "Awaiting gamestate..." with "Sys_SendPacket: Invalid argument" printed on stdout.

**Comment by xplshn** [comment]
It seems OmegA engine has a patch for that, but I'm not good at coding...

**Comment by AsciiWolf** [comment]
Wait... Was this issue fixed (in the main Quake3e branch, not OmegA)?

**Comment by xplshn** [comment]
It apparently only displays the issue when ran in the 22.08 runtime

**Comment by AsciiWolf** [comment]
Interesting!
